export const NEW_SERVICE_ACTIONS = {
    SET_CLEAN_TYPE: "SET_CLEAN_TYPE",
    SET_SERVICE_TYPE: 'SET_SERVICE_TYPE',
    SET_SERVICE_DAY: 'SET_SERVICE_DAY',
    SET_SERVICE_BEGIN_AT: 'SET_SERVICE_BEGIN_AT',
    SET_SERVICE_ADDRESS: 'SET_SERVICE_ADDRESS',
    SET_SERVICE_HOURS: 'SET_SERVICE_HOURS'
};